// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddTodo(arg1, arg2) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2);
}

export function ArgoLogin() {
  return window['go']['main']['App']['ArgoLogin']();
}

export function AzAccounts() {
  return window['go']['main']['App']['AzAccounts']();
}

export function AzLogin() {
  return window['go']['main']['App']['AzLogin']();
}

export function AzSetSubscription(arg1) {
  return window['go']['main']['App']['AzSetSubscription'](arg1);
}

export function Cleanup(arg1, arg2) {
  return window['go']['main']['App']['Cleanup'](arg1, arg2);
}

export function CloseTerm(arg1) {
  return window['go']['main']['App']['CloseTerm'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function Deploy(arg1) {
  return window['go']['main']['App']['Deploy'](arg1);
}

export function DeployStatus() {
  return window['go']['main']['App']['DeployStatus']();
}

export function DoneAgent(arg1) {
  return window['go']['main']['App']['DoneAgent'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function Merge(arg1, arg2, arg3) {
  return window['go']['main']['App']['Merge'](arg1, arg2, arg3);
}

export function NewSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewSession'](arg1, arg2, arg3);
}

export function OpenTerm(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenTerm'](arg1, arg2, arg3);
}

export function Overview(arg1) {
  return window['go']['main']['App']['Overview'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Projects() {
  return window['go']['main']['App']['Projects']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveWorktree(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorktree'](arg1, arg2);
}

export function ResizeTerm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerm'](arg1, arg2, arg3);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SearchTranscripts(arg1) {
  return window['go']['main']['App']['SearchTranscripts'](arg1);
}

export function SendSkill(arg1, arg2) {
  return window['go']['main']['App']['SendSkill'](arg1, arg2);
}

export function SessionPreview(arg1) {
  return window['go']['main']['App']['SessionPreview'](arg1);
}

export function SetActiveTerm(arg1) {
  return window['go']['main']['App']['SetActiveTerm'](arg1);
}

export function SetMainBranch(arg1, arg2) {
  return window['go']['main']['App']['SetMainBranch'](arg1, arg2);
}

export function StartTodoSession(arg1) {
  return window['go']['main']['App']['StartTodoSession'](arg1);
}

export function Timeline() {
  return window['go']['main']['App']['Timeline']();
}

export function Todos() {
  return window['go']['main']['App']['Todos']();
}

export function UpdateTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2, arg3);
}

export function WorktreeDiff(arg1) {
  return window['go']['main']['App']['WorktreeDiff'](arg1);
}

export function WriteTerm(arg1, arg2) {
  return window['go']['main']['App']['WriteTerm'](arg1, arg2);
}
