// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function AddProject(arg1:string):Promise<string>;

export function AddTodo(arg1:string,arg2:string):Promise<void>;

export function ArgoLogin():Promise<void>;

export function AzAccounts():Promise<Array<main.AzAccount>>;

export function AzLogin():Promise<void>;

export function AzSetSubscription(arg1:string):Promise<void>;

export function Cleanup(arg1:string,arg2:string):Promise<string>;

export function CloseTerm(arg1:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function Deploy(arg1:string):Promise<string>;

export function DeployStatus():Promise<main.DeployStatus>;

export function DoneAgent(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function Merge(arg1:string,arg2:string,arg3:string):Promise<string>;

export function NewSession(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function OpenTerm(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Overview(arg1:boolean):Promise<core.Overview>;

export function PickFolder():Promise<string>;

export function Projects():Promise<Array<string>>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:string):Promise<void>;

export function ResizeTerm(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveImage(arg1:string):Promise<string>;

export function SearchTranscripts(arg1:string):Promise<Array<main.SearchHit>>;

export function SendSkill(arg1:string,arg2:string):Promise<void>;

export function SessionPreview(arg1:string):Promise<string>;

export function SetActiveTerm(arg1:string):Promise<void>;

export function SetMainBranch(arg1:string,arg2:string):Promise<void>;

export function StartTodoSession(arg1:number):Promise<string>;

export function Timeline():Promise<Array<main.TimelineEntry>>;

export function Todos():Promise<Array<main.TodoInfo>>;

export function UpdateTodo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function WorktreeDiff(arg1:string):Promise<string>;

export function WriteTerm(arg1:string,arg2:string):Promise<void>;
