// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function AddProject(arg1:string):Promise<string>;

export function AgentVendors():Promise<Array<core.AgentVendorOption>>;

export function ArgoLogin():Promise<void>;

export function AzAccounts():Promise<Array<main.AzAccount>>;

export function AzLogin():Promise<void>;

export function AzSetSubscription(arg1:string):Promise<void>;

export function Board(arg1:string):Promise<core.Board>;

export function BoardArchive(arg1:string,arg2:number):Promise<core.Board>;

export function BreakConfig():Promise<core.BreakConfig>;

export function BreakHeartbeat(arg1:boolean):Promise<core.BreakAdvice>;

export function BreakOver():Promise<void>;

export function Breaks():Promise<core.BreakAdvice>;

export function BuildInfo():Promise<string>;

export function Cleanup(arg1:string,arg2:string):Promise<string>;

export function ClearNotch(arg1:string):Promise<void>;

export function CloseTerm(arg1:string):Promise<void>;

export function DeleteSessionAutomation(arg1:string,arg2:string):Promise<void>;

export function Deploy(arg1:string):Promise<string>;

export function DeployStatus():Promise<main.DeployStatus>;

export function DiscardQueuedMessage(arg1:string,arg2:string):Promise<void>;

export function DoneAgent(arg1:string):Promise<void>;

export function EndBreak():Promise<void>;

export function GitGraph(arg1:string,arg2:number):Promise<core.GitGraph>;

export function HandoffSession(arg1:string,arg2:string):Promise<void>;

export function KillSession(arg1:string,arg2:string):Promise<void>;

export function LaterSession(arg1:string):Promise<void>;

export function MarkSeen(arg1:string):Promise<void>;

export function Merge(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MigrateDockSessions(arg1:Array<string>):Promise<Array<main.DockSessionRef>>;

export function NewDockSession(arg1:string):Promise<main.DockSessionRef>;

export function NewSession(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function NewSessionWithVendor(arg1:string,arg2:boolean,arg3:string,arg4:string):Promise<string>;

export function NewTermSession(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function NewTermSessionFor(arg1:string):Promise<string>;

export function OpenTerm(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function Overview(arg1:boolean):Promise<core.Overview>;

export function PickFolder():Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:string):Promise<void>;

export function ReopenSession(arg1:string):Promise<void>;

export function ReorderProjects(arg1:Array<string>):Promise<void>;

export function ResizeTerm(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondToNotch(arg1:main.NotchResponse):Promise<void>;

export function RetryQueuedMessage(arg1:string,arg2:string):Promise<void>;

export function SaveImage(arg1:string):Promise<string>;

export function SaveSessionAutomation(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:boolean):Promise<core.SessionAutomation>;

export function SearchTranscripts(arg1:string):Promise<main.SearchResult>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendSkill(arg1:string,arg2:string):Promise<void>;

export function SessionAutomation(arg1:string):Promise<core.SessionAutomation>;

export function SessionLinks(arg1:string):Promise<main.SessionLinksResult>;

export function SessionPreview(arg1:string):Promise<main.SessionPreviewResult>;

export function SetActiveTerm(arg1:string):Promise<void>;

export function SetBreakConfig(arg1:core.BreakConfig):Promise<void>;

export function SetMainBranch(arg1:string,arg2:string):Promise<void>;

export function ShowNotchEvent(arg1:main.NotchEvent):Promise<void>;

export function SnoozeBreak():Promise<void>;

export function StartBoardItem(arg1:string,arg2:string):Promise<string>;

export function Stats(arg1:number):Promise<core.Stats>;

export function SwitchSessionVendor(arg1:string,arg2:string):Promise<void>;

export function TakeBreak():Promise<void>;

export function Timeline():Promise<main.TimelineResult>;

export function WorktreeDiff(arg1:string,arg2:string):Promise<string>;

export function WriteTerm(arg1:string,arg2:string):Promise<void>;

export function Zeitgeist():Promise<core.ZgInfo>;

export function ZeitgeistPause():Promise<void>;

export function ZeitgeistResume():Promise<void>;

export function ZeitgeistStart(arg1:string):Promise<core.ZgProject>;

export function ZeitgeistStop(arg1:string):Promise<core.ZgStopped>;
