// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function AddTodo(arg1:string,arg2:string):Promise<void>;

export function ArgoLogin():Promise<void>;

export function AzLogin():Promise<void>;

export function Cleanup(arg1:string,arg2:string):Promise<string>;

export function CloseTerm(arg1:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function Deploy(arg1:string):Promise<string>;

export function DeployStatus():Promise<main.DeployStatus>;

export function DoneAgent(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function Merge(arg1:string,arg2:string,arg3:string):Promise<string>;

export function NewSession(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function OpenTerm(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Overview():Promise<core.Overview>;

export function Projects():Promise<Array<string>>;

export function RemoveWorktree(arg1:string,arg2:string):Promise<void>;

export function ResizeTerm(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendSkill(arg1:string,arg2:string):Promise<void>;

export function SetMainBranch(arg1:string,arg2:string):Promise<void>;

export function StartTodoSession(arg1:number):Promise<string>;

export function Todos():Promise<Array<main.TodoInfo>>;

export function UpdateTodo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function WriteTerm(arg1:string,arg2:string):Promise<void>;
