// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDivider(arg1) {
  return window['go']['main']['App']['AddDivider'](arg1);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AgentVendors() {
  return window['go']['main']['App']['AgentVendors']();
}

export function ArgoLogin() {
  return window['go']['main']['App']['ArgoLogin']();
}

export function AzAccounts() {
  return window['go']['main']['App']['AzAccounts']();
}

export function AzLogin() {
  return window['go']['main']['App']['AzLogin']();
}

export function AzSetSubscription(arg1) {
  return window['go']['main']['App']['AzSetSubscription'](arg1);
}

export function Board(arg1) {
  return window['go']['main']['App']['Board'](arg1);
}

export function BoardArchive(arg1, arg2) {
  return window['go']['main']['App']['BoardArchive'](arg1, arg2);
}

export function BreakConfig() {
  return window['go']['main']['App']['BreakConfig']();
}

export function BreakHeartbeat(arg1) {
  return window['go']['main']['App']['BreakHeartbeat'](arg1);
}

export function BreakOver() {
  return window['go']['main']['App']['BreakOver']();
}

export function Breaks() {
  return window['go']['main']['App']['Breaks']();
}

export function BuildInfo() {
  return window['go']['main']['App']['BuildInfo']();
}

export function Cleanup(arg1, arg2) {
  return window['go']['main']['App']['Cleanup'](arg1, arg2);
}

export function ClearNotch(arg1) {
  return window['go']['main']['App']['ClearNotch'](arg1);
}

export function CloseTerm(arg1) {
  return window['go']['main']['App']['CloseTerm'](arg1);
}

export function DeleteSessionAutomation(arg1, arg2) {
  return window['go']['main']['App']['DeleteSessionAutomation'](arg1, arg2);
}

export function Deploy(arg1) {
  return window['go']['main']['App']['Deploy'](arg1);
}

export function DeployStatus() {
  return window['go']['main']['App']['DeployStatus']();
}

export function DiscardQueuedMessage(arg1, arg2) {
  return window['go']['main']['App']['DiscardQueuedMessage'](arg1, arg2);
}

export function DoneAgent(arg1) {
  return window['go']['main']['App']['DoneAgent'](arg1);
}

export function EndBreak() {
  return window['go']['main']['App']['EndBreak']();
}

export function GitGraph(arg1, arg2) {
  return window['go']['main']['App']['GitGraph'](arg1, arg2);
}

export function HandoffSession(arg1, arg2) {
  return window['go']['main']['App']['HandoffSession'](arg1, arg2);
}

export function KillSession(arg1, arg2) {
  return window['go']['main']['App']['KillSession'](arg1, arg2);
}

export function LaterSession(arg1) {
  return window['go']['main']['App']['LaterSession'](arg1);
}

export function MarkSeen(arg1) {
  return window['go']['main']['App']['MarkSeen'](arg1);
}

export function Merge(arg1, arg2, arg3) {
  return window['go']['main']['App']['Merge'](arg1, arg2, arg3);
}

export function MigrateDockSessions(arg1) {
  return window['go']['main']['App']['MigrateDockSessions'](arg1);
}

export function MoveSidebarItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MoveSidebarItem'](arg1, arg2, arg3, arg4, arg5);
}

export function NewDockSession(arg1) {
  return window['go']['main']['App']['NewDockSession'](arg1);
}

export function NewSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewSession'](arg1, arg2, arg3);
}

export function NewSessionWithVendor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NewSessionWithVendor'](arg1, arg2, arg3, arg4);
}

export function NewTermSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewTermSession'](arg1, arg2, arg3);
}

export function NewTermSessionFor(arg1) {
  return window['go']['main']['App']['NewTermSessionFor'](arg1);
}

export function OpenTerm(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenTerm'](arg1, arg2, arg3, arg4);
}

export function Overview(arg1) {
  return window['go']['main']['App']['Overview'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RemoveDivider(arg1) {
  return window['go']['main']['App']['RemoveDivider'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveWorktree(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorktree'](arg1, arg2);
}

export function RenameDivider(arg1, arg2) {
  return window['go']['main']['App']['RenameDivider'](arg1, arg2);
}

export function ReopenSession(arg1) {
  return window['go']['main']['App']['ReopenSession'](arg1);
}

export function ResizeTerm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerm'](arg1, arg2, arg3);
}

export function RespondToNotch(arg1) {
  return window['go']['main']['App']['RespondToNotch'](arg1);
}

export function RetryQueuedMessage(arg1, arg2) {
  return window['go']['main']['App']['RetryQueuedMessage'](arg1, arg2);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SaveSessionAutomation(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveSessionAutomation'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SearchTranscripts(arg1) {
  return window['go']['main']['App']['SearchTranscripts'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendSkill(arg1, arg2) {
  return window['go']['main']['App']['SendSkill'](arg1, arg2);
}

export function SessionAutomation(arg1) {
  return window['go']['main']['App']['SessionAutomation'](arg1);
}

export function SessionLinks(arg1) {
  return window['go']['main']['App']['SessionLinks'](arg1);
}

export function SessionPreview(arg1) {
  return window['go']['main']['App']['SessionPreview'](arg1);
}

export function SetActiveTerm(arg1) {
  return window['go']['main']['App']['SetActiveTerm'](arg1);
}

export function SetBreakConfig(arg1) {
  return window['go']['main']['App']['SetBreakConfig'](arg1);
}

export function SetDividerCollapsed(arg1, arg2) {
  return window['go']['main']['App']['SetDividerCollapsed'](arg1, arg2);
}

export function SetMainBranch(arg1, arg2) {
  return window['go']['main']['App']['SetMainBranch'](arg1, arg2);
}

export function ShowNotchEvent(arg1) {
  return window['go']['main']['App']['ShowNotchEvent'](arg1);
}

export function SnoozeBreak() {
  return window['go']['main']['App']['SnoozeBreak']();
}

export function StartBoardItem(arg1, arg2) {
  return window['go']['main']['App']['StartBoardItem'](arg1, arg2);
}

export function Stats(arg1) {
  return window['go']['main']['App']['Stats'](arg1);
}

export function SwitchSessionVendor(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchSessionVendor'](arg1, arg2, arg3);
}

export function TakeBreak() {
  return window['go']['main']['App']['TakeBreak']();
}

export function Timeline() {
  return window['go']['main']['App']['Timeline']();
}

export function WorktreeDiff(arg1, arg2) {
  return window['go']['main']['App']['WorktreeDiff'](arg1, arg2);
}

export function WriteTerm(arg1, arg2) {
  return window['go']['main']['App']['WriteTerm'](arg1, arg2);
}

export function Zeitgeist() {
  return window['go']['main']['App']['Zeitgeist']();
}

export function ZeitgeistPause() {
  return window['go']['main']['App']['ZeitgeistPause']();
}

export function ZeitgeistResume() {
  return window['go']['main']['App']['ZeitgeistResume']();
}

export function ZeitgeistStart(arg1) {
  return window['go']['main']['App']['ZeitgeistStart'](arg1);
}

export function ZeitgeistStop(arg1) {
  return window['go']['main']['App']['ZeitgeistStop'](arg1);
}
