package remote

// HostAPIMethods nennt jede Methode, die das Frontend heute an die App
// gebunden bekommt (Wails bindet alle exportierten *App-Methoden aus app/).
// Die Liste ist die kanonische Nahtstelle aus D1: Das app-Modul hält mit
// app/hostapi.go ein Go-Interface mit genau diesen Namen und Signaturen, die
// lokale Implementierung ist die heutige *App, die remote-Implementierung ist
// der Client aus diesem Paket. Wer hier einen Namen ergänzt, muss ihn in
// RemoteActionPolicy klassifizieren — der Policy-Test schlägt sonst fehl.
var HostAPIMethods = []string{
	"AddDivider",
	"AddProject",
	"AddReviewComment",
	"AgentVendors",
	"ArgoLogin",
	"AzAccounts",
	"AzLogin",
	"AzSetSubscription",
	"Board",
	"BoardArchive",
	"BreakConfig",
	"BreakHeartbeat",
	"BreakOver",
	"Breaks",
	"BuildInfo",
	"Cleanup",
	"ClearNotch",
	"CloseTerm",
	"CompleteCommands",
	"CompleteFiles",
	"DeleteReviewComment",
	"DeleteSessionAutomation",
	"Deploy",
	"DeployStatus",
	"DiscardQueuedMessage",
	"DiscardSentReview",
	"DiscardSession",
	"DoneAgent",
	"EditReviewComment",
	"EndBreak",
	"FreshStartSession",
	"GitGraph",
	"HandoffSession",
	"Inbox",
	"KillSession",
	"LaterSession",
	"MarkSeen",
	"Merge",
	"MigrateDockSessions",
	"MoveSidebarItem",
	"NewDockSession",
	"NewSession",
	"NewSessionWithVendor",
	"NewTermSession",
	"NewTermSessionFor",
	"NotificationsEnabled",
	"OpenReview",
	"OpenTerm",
	"Overview",
	"PickFolder",
	"PromptLinePattern",
	"RemoveDivider",
	"RemoveProject",
	"RemoveWorktree",
	"RenameDivider",
	"ReopenSession",
	"ResizeTerm",
	"RespondToNotch",
	"ResumeSession",
	"RetryQueuedMessage",
	"ReviewPreview",
	"SaveImage",
	"SaveSessionAutomation",
	"SearchTranscripts",
	"SendMessage",
	"SendReview",
	"SendSkill",
	"SentReviews",
	"SessionAutomation",
	"SessionConversation",
	"SessionLinks",
	"SessionPreview",
	"SetActiveTerm",
	"SetBreakConfig",
	"SetDividerCollapsed",
	"SetMainBranch",
	"SetNotificationsEnabled",
	"SetSessionService",
	"ShowNotchEvent",
	"SnoozeBreak",
	"StartBoardItem",
	"Stats",
	"StructuredDiff",
	"SwitchSessionVendor",
	"TakeBreak",
	"Timeline",
	"WatchConversation",
	"WorktreeDiff",
	"WriteTerm",
	"Zeitgeist",
	"ZeitgeistPause",
	"ZeitgeistResume",
	"ZeitgeistStart",
	"ZeitgeistStop",
}
